name: flutter_base
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  get: ^4.6.5
  retrofit: ^4.0.1
  # api_annotation:
  #   path: ./packages/api_annotation
  flutter_animate: ^4.2.0+1
  shared_preferences: ^2.2.2
  collection: ^1.17.0
  connectivity_plus: ^5.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.1+1
  pretty_dio_logger: ^1.3.1
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
