name: flutter_base
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  get: ^4.6.5
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.1+1
  pretty_dio_logger: ^1.3.1

flutter:
  uses-material-design: true
