builders:
  api_annotation:
    import: "package:api_annotation/src/builder.dart"
    builder_factories: ["buildApiAnnotation"]
    build_extensions: { ".dart": [".api_annotation.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
